# Creating NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```
* Initialise arrays of fixed size (when the size is known) 

The following ways are commonly used:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [2]:
# importing the NumPy library

import numpy as np

In [3]:
# creating an array with 4 elements and increments of a fixed step size
# default step size is one
np_1 = np.arange(1,6)


# creating an array of zeroes with 5 elements
np_2 = np.zeros(5)

In [3]:
# checking the created array: np_1
print(np_1)

[1 2 3 4]


In [4]:
# checking the created array:np_2
print(np_2)

[0. 0. 0. 0. 0.]


In [6]:
# data type of np_2
np_2.dtype


dtype('float64')

In [8]:
# specifying the data type of the array in the provided attribute

np_2=np.zeros(5,dtype=int)
np_2

array([0, 0, 0, 0, 0])

In [11]:
# adding the two arrays: np_1 and np_2
print(np_1 + np_2)

[1. 2. 3. 4. 5.]


In [12]:
# check the dimension of the arrays
# array np_1
np_1.size


5

In [13]:
# check the dimension of the arrays
# array np_2
np_2.size


5

In [16]:
# creating a third array with all the 5 elements as ones

np_3 = np.ones(5,dtype=int)

# checking the created array:np_3
print(np_3)

[1 1 1 1 1]


In [17]:
# check the dimension of the arrays
# array np_2
np_2.size


5

In [18]:
# subtracting the array np_3 from array np_2

print(np_2 - np_3)

[-1. -1. -1. -1. -1.]


In [ ]:
# creating an array of fixed length
np_4 = 

# checking the created array:np_4
print(np_4)

In [40]:
import numpy as np
n=int(input("enter the digit"))

x = np.ones((n,n),dtype=int)
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)


enter the digit6
Original array:
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
1 on the border and 0 inside in the array
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [ ]:
# checking the created array:np_1
np_1

In [5]:
# squaring the terms of np_1





IndexError: index 9 is out of bounds for axis 0 with size 5

In [9]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [11]:
np.eye(3,k=1)

np.random.random(size=4)

array([0.73472602, 0.49955814, 0.89778136, 0.77339257])

In [13]:
# getting the absolute value of the elements
np.absolute

<ufunc 'absolute'>

In [ ]:
# np.sin()
# np.cos()

In [15]:
import numpy as np 

# Given array
a = np.array([[4, 3, 1], [5, 7, 0], [9, 9, 3], [8, 2, 4]])

# Read the values of m and n
import sys
lines = sys.stdin.readlines(2)
m = int(lines[0])
n = int(lines[1])

# Write your code for swapping here
a[[m,n],:] = a[[n,m],:]
# Print the array after swapping
print(a)

IndexError: list index out of range

In [ ]:
# np.log()

### Empty arrays

In [19]:
# Creating empty arrays

x = np.arange(1, 6)
y = np.empty(5)
np.multiply(x,10,out = y)
y

# filling the empty array


array([10., 20., 30., 40., 50.])

In [ ]:
# printing the output obtained above
y

### Aggregation of array elements

In [20]:
# Reducing the elements to a single value based on addition
np.add.reduce(x)


15

In [21]:
# Cummulative addition of elements at each element
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [ ]:
np.linalg

In [13]:
help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decomposition of a matrix
    - svd             Singular value decomposition 

## Additional functions to initialize arrays in NumPy

Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
* ```np.random.random()```: Create array of random numbers between 0 and 1
-  `np.random.randint()`: Create a random array of integers within a particular range

In [22]:
# Creating a 4 x 3 array of 7s using np.full()
# The default data type here is int only
np.full((4,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [23]:
# Given an array, np.tile() creates a new array by repeating the given array for any number of times that you want
# The default data type her is int only
arr = ([0, 1, 2])
np.tile(arr, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [24]:
# You can also create multidimensional arrays using np.tile()
np.tile(arr, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [25]:
# Create a 3 x 3 identity matrix using np.eye()
# The default data type here is float. So if we want integer values, we need to specify the dtype to be int
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [26]:
# Create a 3 x 3 array of random numbers between 0 and 1
np.random.random([3, 4])

array([[0.51254134, 0.57007779, 0.71488668, 0.33011717],
       [0.28776647, 0.81019393, 0.47695929, 0.66413899],
       [0.13928906, 0.44768615, 0.13164267, 0.35269421]])

In [27]:
# Create a 4 x 4 random array of integers ranging from 0 to 9
np.random.randint(0, 10, (4,4))

array([[9, 6, 8, 2],
       [8, 0, 4, 5],
       [4, 7, 1, 0],
       [9, 6, 5, 1]])

In [5]:
import numpy as np
array_1=np.array([[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20]])
array_1
tt=np.array([[1, 5],
 [3, 7],
 [4, 9]])

x=np.reshape(tt, (1, -1))

x




array([[1, 5, 3, 7, 4, 9]])