# Manipulating Arrays

Here are two techniques that can be used to change or manipulayte the structure of arrays:
*  Stacking
*  Reshaping

### Stacking

In [4]:
import numpy as np

dd=np.arange(5)
dd1=np.arange(5,10)
dd
dd1

array([5, 6, 7, 8, 9])

In [8]:
#importing the NumPy library
import numpy as np

# Creating two 1-D arrays with 5 elements using arange
arr_1 = np.arange(5)
arr_2 = np.arange(5,10)
arr_1
arr_2


array([5, 6, 7, 8, 9])

In [12]:
# Horizonal stacking - Appending the elements in the same row
p=np.hstack((arr_1,arr_2))
p

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Vertical stacking - Increasing the number of row


# Storing the stacked array for further operations
arr_3 = np.vstack((arr_1,arr_2))
arr_3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
# Checking the dimensions of the array
arr_3.ndim


2

In [15]:
# Printing the created array
arr_3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
# Number of rows and columns in the array
arr_3.shape

(2, 5)

### Reshaping

In [25]:
# Creating an array of first ten natural numbers
arr_4 = np.arange(10)

# Printing the created array
arr_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# Reshaping the 1D array into a 2D array with 2 elements in five rows
arr_5 = np.arange(5,10)
arr_5

array([5, 6, 7, 8, 9])

In [34]:
# Checking the rows and columns in the created array
arr_5= np.hstack((arr_4,arr_5))
arr_5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 6,
       7, 8, 9])

In [45]:
# Creating a 2D array with 4 elements in five rows (elements from 20 to 39)
arr_6 = np.arange(20,40).reshape(5,4)


# Checking the rows and columns in the created array
arr_6

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [ ]:
# Stacking arr_5 and arr_6


In [ ]:
# Check the structure of arr_6


In [ ]:
# Reshape the arr_6 to vertically stack with arr_5 
arr_6 = 
arr_6

In [ ]:
# Stacking arr_5 and arr_6


In [46]:
arr_t=np.arange(0,132)

In [51]:
nn=arr_t.reshape(11,12)
nn

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131]])

In [52]:
nn[8][4]

100

In [58]:
rrr=np.array(range(1,11*12+1))
rrr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132])

In [66]:
rrr.reshape(11,12)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36],
       [ 37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48],
       [ 49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72],
       [ 73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96],
       [ 97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108],
       [109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132]])

In [73]:
mm=np.array([[1, 5],
 [3, 7],
 [4, 9]])

In [69]:
mm

array([[1, 5],
       [3, 7],
       [4, 9]])

array([1, 5, 3, 7, 4, 9])

In [74]:
np.reshape(mm,2)

ValueError: cannot reshape array of size 6 into shape (2,)